CREATE TABLE user_attempts (
    user_id       BIGINT  PRIMARY KEY REFERENCES app_user(id) ON DELETE CASCADE,
    attempts      INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    last_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
